---
title: "Quiz3 In Class Portion"
author: "Grace Wysocki"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Complete this quiz in a .Rmd file. To turn in the quiz, push both a .Rmd file and a knitted .html file to your GitHub site.

Statement of Integrity: Copy and paste the following statement and then sign your name (by typing it) on the line below.

“All work presented is my own. I have not communicated with or worked with anyone else on this quiz.” Grace Wysocki

Collaboration Reminder: You may not communicate with or work with anyone else on this quiz, but you may use any of our course materials or materials on the Internet.



Question 1 (5 points). Suppose you do the following:

You go to your GitHub site and make a change to the README file (adding a sentence, for example).
In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
You attempt to push the new file to your GitHub site.
Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

Before you push, you need to add a commit message to be displayed in GitHub.

Question 2 (6 points). Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

One advantage is that you can easily share copies of your work with other for collaboration.
A second advantatge is that you can save copies of your work to GitHub, and then continue working on that same file in RStudio. This meas you dont have to worry if you make mistakes when playing around with datasets beacuse you will always have an original copy saved.

Question 3 (6 points). Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

6) Be open to changing our methods and conclusions in response to new knowledge.

I think this principle would be hard for many to execute for reasons of ones own pride. Imagine that you spend months or maybe even years of your life developing what you think is a life changing model, and new information comes in to debunk one of your points or conclusions you made. I think it would be very difficult for some one to change all of their work just because on newly found idea debunks it. 

Question 4 (6 points). The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

The author used the example of data found from people who died from gun violence in the United States in the year 2013. The author showed emotion by individually plotting each person's death and even including the years of life that where stolen from them in a count. An argument that could be made against embracing emotion in data science is that by adding emotion you are manipulating your data to make your audience feel a specific emotion which places some bias on the data visualization. Data science has no room for forcing emotions onto people. You should rather present your data in a way that allows for individaul interpretation.

Question 5 (2 points). These two points are given for committing your .Rmd and .html files with a commit message correctly, and pushing them to your GitHub site.